name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  extract_version:
    runs-on: ubuntu-latest
    name: Extract version
    outputs:
      version: ${{ steps.version.outputs.value }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Version
        id: version
        run: echo "value=${GITHUB_REF#refs/*/v}" >> "$GITHUB_OUTPUT"

  create_release:
    runs-on: ubuntu-latest
    needs: extract_version
    name: Create release on GitHub
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: gh release create v${{ needs.extract_version.outputs.version }} --generate-notes -t "Release ${{ needs.extract_version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
        name: Creates a release in GitHub

  docker:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    needs: [extract_version, create_release]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: guyeise5/proxy:${{ needs.extract_version.outputs.version }},guyeise5/proxy:latest
